# Generated by Django 4.2.13 on 2024-06-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Проданный товар', 'verbose_name_plural': 'Проданные товары'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='createa_timestamp',
            new_name='created_timestamp',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_addres',
            new_name='delivery_address',
        ),
    ]
